sudo: false
os:
  - linux
  - osx
  - windows
# https://docs.travis-ci.com/user/reference/osx/
osx_image: xcode9.3
language: node_js
node_js:
  - '8'
  - '10'
install:
  - npm i npminstall && npminstall
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install jdk8          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then export PATH=$PATH:"/c/Program Files/Java/jdk1.8.0_201/bin"          ; fi
  - java -version
script:
  - npm run ci
after_success:
  - npminstall codecov && codecov --disable=gcov -f .nyc_output/*.json
